
name: 'stripe'
version: '1.0'

source-paths: ["models"]
analysis-paths: ["analysis"]
target-path: "target"
clean-targets: ["target"]
test-paths: ["test"]
data-paths: ["data"]

models:
  stripe:
    enabled: true
    materialized: view
    vars:
      events_table: "{{ ref('all_events') }}"

profile: code-climate
