stripe_subscription_events:
  constraints:
    not_null:
      - customer_id
      - created_at
      - period_start
      - period_end
      - event_type
      - status
      - plan_interval
      - mrr
    accepted_values:
      - {field: plan_interval, values: ['month', 'year']}
    relationships:
      - {from: customer_id, to: stripe_customers, field: id}

stripe_discount_events:
  constraints:
    relationships:
      - {from: coupon_id, to: stripe_coupons, field: id}
