stripe_subscription_events:
  constraints:
    not_null:
      - customer_id
      - created_at
      - period_start
      - period_end
      - event_type
      - status
      - plan_interval
      - mrr

    accepted_values:
      - {field: plan_interval, values: ['month', 'year']}
    relationships:
      - {from: customer_id, to: stripe_customers, field: id}

stripe_coupons:
  constraints:
    not_null:
      - id
      - created_at
    unique:
      - id

stripe_customers:
  constraints:
    not_null:
      - id
      - name
      - email
      - created_at
    unique:
      - id

stripe_discount_events:
  constraints:
    relationships:
      - {from: coupon_id, to: stripe_coupons, field: id}

stripe_mrr_amortized:
  constraints:
    not_null:
      - customer_id
      - date_day
      - mrr
    unique:
      - customer_id || '|' || date_day

stripe_mrr_discounted:
  constraints:
    not_null:
      - customer_id
      - date_day
      - mrr
    unique:
      - customer_id || '|' || date_day

stripe_discounts:
  constraints:
    not_null:
      - customer_id
      - date_day
      - coupon_id
      - discount_type
      - discount_value
    accepted_values:
      - {field: discount_type, values: ['amount', 'percent']}
    unique:
      - customer_id || '|' || date_day
